# Generated by Django 5.2.7 on 2025-11-01 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='grupos_musculares/')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Grupos Musculares',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('musculos_trabajados', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='workout_app.grupomuscular')),
            ],
            options={
                'ordering': ['grupo_muscular', 'orden'],
            },
        ),
    ]
